import * as vscode from "vscode";
import * as fs from "node:fs";
import * as path from "node:path";
import type { Prompt } from "../core/prompt";
import {
  findTemplate,
  getTemplatesInDisplayOrder,
  renderPromptDraft,
  templateRequiresPullRequest,
  type PromptTemplateDefinition,
} from "../core/templates";
import type { PromptStore } from "../store/prompt-store";
import { ChildPromptPreviewProvider } from "./child-preview";
import type { PromptTreeItem } from "./tree";

type PromptRef = string | PromptTreeItem | undefined;

function resolvePromptId(ref: PromptRef): string | undefined {
  return typeof ref === "string" ? ref : ref?.prompt.id;
}

/**
 * Stores workspace files as relative paths (portable if `.sobek/` is shared)
 * and files outside the workspace as absolute paths — plans generated by
 * Claude Code can live anywhere on disk, like Thoth's linked documents.
 */
function toPlanPath(workspaceRoot: string, fsPath: string): string {
  const relative = path.relative(workspaceRoot, fsPath);
  if (relative.startsWith("..") || path.isAbsolute(relative)) {
    return fsPath;
  }
  return relative.replace(/\\/g, "/");
}

async function pickPlanFile(workspaceRoot: string): Promise<string | undefined> {
  const files = await vscode.workspace.findFiles(
    "**/*.md",
    "{**/node_modules/**,**/.sobek/**,**/.git/**,**/dist/**,**/build/**}",
    500
  );
  const browseItem = {
    label: "$(folder-opened) Procurar arquivo...",
    description: "Selecionar um Markdown em qualquer diretório",
    action: "browse" as const,
  };
  const typeItem = {
    label: "$(edit) Digitar caminho...",
    description: "Informar o caminho absoluto ou relativo do plano",
    action: "type" as const,
  };
  const fileItems = files
    .map((uri) => ({
      label: path.basename(uri.fsPath),
      description: path.relative(workspaceRoot, uri.fsPath).replace(/\\/g, "/"),
      uri,
      action: "pick" as const,
    }))
    .sort((a, b) => a.description.localeCompare(b.description));

  const picked = await vscode.window.showQuickPick([browseItem, typeItem, ...fileItems], {
    placeHolder: "Plano Markdown (ex.: plano gerado pelo Claude Code — pode estar fora do workspace)",
    matchOnDescription: true,
  });
  if (!picked) {
    return undefined;
  }

  if (picked.action === "browse") {
    const selection = await vscode.window.showOpenDialog({
      canSelectMany: false,
      defaultUri: vscode.Uri.file(workspaceRoot),
      openLabel: "Vincular plano",
      filters: { Markdown: ["md", "markdown"] },
    });
    return selection?.[0] ? toPlanPath(workspaceRoot, selection[0].fsPath) : undefined;
  }

  if (picked.action === "type") {
    const typed = await vscode.window.showInputBox({
      prompt: "Caminho do plano Markdown (absoluto ou relativo ao workspace)",
      placeHolder: "Ex.: C:\\Users\\voce\\planos\\plano.md ou docs/plano.md",
      ignoreFocusOut: true,
      validateInput: (value) => {
        if (value.trim().length === 0) {
          return "Informe um caminho.";
        }
        const resolved = path.resolve(workspaceRoot, value.trim());
        return fs.existsSync(resolved) ? undefined : "Arquivo não encontrado.";
      },
    });
    if (!typed) {
      return undefined;
    }
    return toPlanPath(workspaceRoot, path.resolve(workspaceRoot, typed.trim()));
  }

  return toPlanPath(workspaceRoot, (picked as { uri: vscode.Uri }).uri.fsPath);
}

async function ensureLinkedPlan(store: PromptStore, prompt: Prompt): Promise<Prompt | undefined> {
  if (prompt.linkedPlan) {
    return prompt;
  }
  const answer = await vscode.window.showInformationMessage(
    "Este prompt ainda não tem um plano vinculado. Prompts filhos são gerados a partir de um plano Markdown.",
    "Vincular plano"
  );
  if (answer !== "Vincular plano") {
    return undefined;
  }
  const planPath = await pickPlanFile(store.root);
  if (!planPath) {
    return undefined;
  }
  return store.setLinkedPlan(prompt.id, {
    path: planPath,
    displayName: path.basename(planPath),
  });
}

async function collectInputs(
  template: PromptTemplateDefinition,
  storedPullRequest: string | undefined
): Promise<{ pullRequestInput?: string; inputs: Record<string, string> } | undefined> {
  const inputs: Record<string, string> = {};
  let pullRequestInput: string | undefined;

  if (templateRequiresPullRequest(template.key)) {
    const prDefinition = template.inputs.find((input) => input.key === "pullRequest");
    pullRequestInput = await vscode.window.showInputBox({
      prompt: prDefinition?.helpText ?? "Informe o número ou link da PR.",
      placeHolder: prDefinition?.placeholder ?? "#123 ou URL da PR",
      value: storedPullRequest,
      ignoreFocusOut: true,
      validateInput: (value) => (value.trim().length === 0 ? "A PR é obrigatória." : undefined),
    });
    if (pullRequestInput === undefined) {
      return undefined;
    }
  }

  for (const input of template.inputs) {
    if (input.key === "pullRequest") {
      continue;
    }
    if (input.multiline) {
      const source = await vscode.window.showQuickPick(
        [
          {
            label: "$(clippy) Colar da área de transferência",
            description: input.placeholder,
            action: "clipboard" as const,
          },
          { label: "$(edit) Digitar manualmente", action: "type" as const },
        ],
        { placeHolder: `${input.label}: como fornecer o conteúdo?`, ignoreFocusOut: true }
      );
      if (!source) {
        return undefined;
      }
      let value: string | undefined;
      if (source.action === "clipboard") {
        value = (await vscode.env.clipboard.readText()).trim();
        if (!value) {
          void vscode.window.showWarningMessage("A área de transferência está vazia.");
          return undefined;
        }
      } else {
        value = await vscode.window.showInputBox({
          prompt: input.placeholder,
          ignoreFocusOut: true,
          validateInput: (candidate) =>
            input.required && candidate.trim().length === 0
              ? `O campo "${input.label}" é obrigatório.`
              : undefined,
        });
        if (value === undefined) {
          return undefined;
        }
      }
      inputs[input.key] = value;
    } else {
      const value = await vscode.window.showInputBox({
        prompt: input.helpText || input.label,
        placeHolder: input.placeholder,
        ignoreFocusOut: true,
        validateInput: (candidate) =>
          input.required && candidate.trim().length === 0
            ? `O campo "${input.label}" é obrigatório.`
            : undefined,
      });
      if (value === undefined) {
        return undefined;
      }
      inputs[input.key] = value;
    }
  }

  return { pullRequestInput, inputs };
}

export type ChildCreatedListener = (child: Prompt, parent: Prompt) => void | Promise<void>;

export function registerGenerateChildCommands(
  context: vscode.ExtensionContext,
  store: PromptStore,
  onChildCreated?: ChildCreatedListener
): void {
  context.subscriptions.push(
    vscode.commands.registerCommand("sobek.linkPlan", async (ref: PromptRef) => {
      const id = resolvePromptId(ref);
      if (!id) {
        return;
      }
      const planPath = await pickPlanFile(store.root);
      if (!planPath) {
        return;
      }
      await store.setLinkedPlan(id, { path: planPath, displayName: path.basename(planPath) });
      void vscode.window.showInformationMessage(`Plano vinculado: ${planPath}`);
    }),

    vscode.commands.registerCommand("sobek.unlinkPlan", async (ref: PromptRef) => {
      const id = resolvePromptId(ref);
      if (!id) {
        return;
      }
      await store.setLinkedPlan(id, undefined);
    }),

    vscode.commands.registerCommand("sobek.generateChildPrompt", async (ref: PromptRef) => {
      const id = resolvePromptId(ref);
      if (!id) {
        return;
      }
      let parent = store.require(id);
      if (parent.parentPromptId) {
        void vscode.window.showWarningMessage("Prompts filhos não geram outros filhos.");
        return;
      }
      if (parent.status === "Archived") {
        void vscode.window.showWarningMessage("Prompt arquivado não gera prompts filhos.");
        return;
      }

      const withPlan = await ensureLinkedPlan(store, parent);
      if (!withPlan?.linkedPlan) {
        return;
      }
      parent = withPlan;
      const plan = parent.linkedPlan!;

      const pickedTemplate = await vscode.window.showQuickPick(
        getTemplatesInDisplayOrder().map((template) => ({
          label: template.isReReview ? `$(sync) ${template.displayName}` : template.displayName,
          description: template.description,
          key: template.key,
        })),
        { placeHolder: "Template do prompt filho" }
      );
      if (!pickedTemplate) {
        return;
      }
      const template = findTemplate(pickedTemplate.key)!;

      const collected = await collectInputs(template, plan.pullRequestReference);
      if (!collected) {
        return;
      }

      let draft;
      try {
        draft = renderPromptDraft({
          template,
          planAbsolutePath: path.resolve(store.root, plan.path),
          planDisplayName: plan.displayName,
          parentPromptContent: parent.content,
          pullRequestInput: collected.pullRequestInput,
          storedPullRequestReference: plan.pullRequestReference,
          inputs: collected.inputs,
        });
      } catch (error) {
        void vscode.window.showErrorMessage((error as Error).message);
        return;
      }

      const title = await vscode.window.showInputBox({
        prompt: "Título do prompt filho",
        value: draft.title,
        ignoreFocusOut: true,
        validateInput: (value) => (value.trim().length === 0 ? "Informe um título." : undefined),
      });
      if (!title) {
        return;
      }

      const child = await store.create({
        title: title.trim(),
        content: draft.content,
        parentPromptId: parent.id,
        targetAgent: template.defaultTargetAgent,
        kind: template.defaultKind,
        status: "Draft",
        sourceTemplateKey: template.key,
      });

      if (collected.pullRequestInput?.trim()) {
        await store.setPullRequestReference(parent.id, collected.pullRequestInput.trim());
      }

      // Stay in the parent's context: read-only preview + copy, no navigation
      // to a child edit surface (Thoth product rule).
      const uri = ChildPromptPreviewProvider.uriFor(child.id, child.title);
      const document = await vscode.workspace.openTextDocument(uri);
      await vscode.languages.setTextDocumentLanguage(document, "markdown");
      await vscode.window.showTextDocument(document, { preview: true });

      const updatedParent = store.require(parent.id);
      const phase = updatedParent.workflow?.currentPhaseName;
      const action = await vscode.window.showInformationMessage(
        phase
          ? `Prompt filho criado. Tarefa avançou para "${phase}".`
          : "Prompt filho criado.",
        "Copiar prompt"
      );
      if (action === "Copiar prompt") {
        await vscode.env.clipboard.writeText(child.content);
      }

      await onChildCreated?.(child, updatedParent);
    })
  );
}
