import * as vscode from "vscode";
import * as fs from "node:fs";
import * as path from "node:path";
import type { Prompt } from "../core/prompt";
import {
  getTemplatesInDisplayOrder,
  renderPromptDraft,
  type PromptTemplateDefinition,
} from "../core/templates";
import type { PromptStore } from "../store/prompt-store";
import { ChildPromptPreviewProvider } from "./child-preview";
import type { PromptTreeItem } from "./tree";

type PromptRef = string | PromptTreeItem | undefined;

function resolvePromptId(ref: PromptRef): string | undefined {
  return typeof ref === "string" ? ref : ref?.prompt.id;
}

/**
 * Stores workspace files as relative paths (portable if `.sobek/` is shared)
 * and files outside the workspace as absolute paths — plans generated by
 * Claude Code can live anywhere on disk, like Thoth's linked documents.
 */
function toPlanPath(workspaceRoot: string, fsPath: string): string {
  const relative = path.relative(workspaceRoot, fsPath);
  if (relative.startsWith("..") || path.isAbsolute(relative)) {
    return fsPath;
  }
  return relative.replace(/\\/g, "/");
}

async function pickPlanFile(workspaceRoot: string): Promise<string | undefined> {
  const files = await vscode.workspace.findFiles(
    "**/*.md",
    "{**/node_modules/**,**/.sobek/**,**/.git/**,**/dist/**,**/build/**}",
    500
  );
  const browseItem = {
    label: `$(folder-opened) ${vscode.l10n.t("Browse files...")}`,
    description: vscode.l10n.t("Pick a Markdown file from any directory"),
    action: "browse" as const,
  };
  const typeItem = {
    label: `$(edit) ${vscode.l10n.t("Type a path...")}`,
    description: vscode.l10n.t("Enter the plan's absolute or relative path"),
    action: "type" as const,
  };
  const fileItems = files
    .map((uri) => ({
      label: path.basename(uri.fsPath),
      description: path.relative(workspaceRoot, uri.fsPath).replace(/\\/g, "/"),
      uri,
      action: "pick" as const,
    }))
    .sort((a, b) => a.description.localeCompare(b.description));

  const picked = await vscode.window.showQuickPick([browseItem, typeItem, ...fileItems], {
    placeHolder: vscode.l10n.t(
      "Markdown plan (e.g. a Claude Code plan — it can live outside the workspace)"
    ),
    matchOnDescription: true,
  });
  if (!picked) {
    return undefined;
  }

  if (picked.action === "browse") {
    const selection = await vscode.window.showOpenDialog({
      canSelectMany: false,
      defaultUri: vscode.Uri.file(workspaceRoot),
      openLabel: vscode.l10n.t("Link plan"),
      filters: { Markdown: ["md", "markdown"] },
    });
    return selection?.[0] ? toPlanPath(workspaceRoot, selection[0].fsPath) : undefined;
  }

  if (picked.action === "type") {
    const typed = await vscode.window.showInputBox({
      prompt: vscode.l10n.t("Path to the Markdown plan (absolute or workspace-relative)"),
      placeHolder: vscode.l10n.t("E.g.: C:\\plans\\plan.md or docs/plan.md"),
      ignoreFocusOut: true,
      validateInput: (value) => {
        if (value.trim().length === 0) {
          return vscode.l10n.t("Enter a path.");
        }
        const resolved = path.resolve(workspaceRoot, value.trim());
        return fs.existsSync(resolved) ? undefined : vscode.l10n.t("File not found.");
      },
    });
    if (!typed) {
      return undefined;
    }
    return toPlanPath(workspaceRoot, path.resolve(workspaceRoot, typed.trim()));
  }

  return toPlanPath(workspaceRoot, (picked as { uri: vscode.Uri }).uri.fsPath);
}

async function ensureLinkedPlan(store: PromptStore, prompt: Prompt): Promise<Prompt | undefined> {
  if (prompt.linkedPlan) {
    return prompt;
  }
  const linkLabel = vscode.l10n.t("Link plan");
  const answer = await vscode.window.showInformationMessage(
    vscode.l10n.t(
      "This prompt has no linked plan yet. Child prompts are generated from a Markdown plan."
    ),
    linkLabel
  );
  if (answer !== linkLabel) {
    return undefined;
  }
  const planPath = await pickPlanFile(store.root);
  if (!planPath) {
    return undefined;
  }
  return store.setLinkedPlan(prompt.id, {
    path: planPath,
    displayName: path.basename(planPath),
  });
}

async function collectInputs(
  template: PromptTemplateDefinition,
  storedPullRequest: string | undefined
): Promise<{ pullRequestInput?: string; inputs: Record<string, string> } | undefined> {
  const inputs: Record<string, string> = {};
  let pullRequestInput: string | undefined;

  if (template.requiresPullRequest) {
    const prDefinition = template.inputs.find((input) => input.key === "pullRequest");
    pullRequestInput = await vscode.window.showInputBox({
      prompt: prDefinition?.helpText ?? vscode.l10n.t("Enter the PR number or URL."),
      placeHolder: prDefinition?.placeholder ?? vscode.l10n.t("#123 or PR URL"),
      value: storedPullRequest,
      ignoreFocusOut: true,
      validateInput: (value) =>
        value.trim().length === 0 ? vscode.l10n.t("The PR is required.") : undefined,
    });
    if (pullRequestInput === undefined) {
      return undefined;
    }
  }

  for (const input of template.inputs) {
    if (input.key === "pullRequest") {
      continue;
    }
    if (input.multiline) {
      const source = await vscode.window.showQuickPick(
        [
          {
            label: `$(clippy) ${vscode.l10n.t("Paste from clipboard")}`,
            description: input.placeholder,
            action: "clipboard" as const,
          },
          { label: `$(edit) ${vscode.l10n.t("Type manually")}`, action: "type" as const },
        ],
        {
          placeHolder: vscode.l10n.t("{0}: how to provide the content?", input.label),
          ignoreFocusOut: true,
        }
      );
      if (!source) {
        return undefined;
      }
      let value: string | undefined;
      if (source.action === "clipboard") {
        value = (await vscode.env.clipboard.readText()).trim();
        if (!value) {
          void vscode.window.showWarningMessage(vscode.l10n.t("The clipboard is empty."));
          return undefined;
        }
      } else {
        value = await vscode.window.showInputBox({
          prompt: input.placeholder,
          ignoreFocusOut: true,
          validateInput: (candidate) =>
            input.required && candidate.trim().length === 0
              ? vscode.l10n.t('The field "{0}" is required.', input.label)
              : undefined,
        });
        if (value === undefined) {
          return undefined;
        }
      }
      inputs[input.key] = value;
    } else {
      const value = await vscode.window.showInputBox({
        prompt: input.helpText || input.label,
        placeHolder: input.placeholder,
        ignoreFocusOut: true,
        validateInput: (candidate) =>
          input.required && candidate.trim().length === 0
            ? vscode.l10n.t('The field "{0}" is required.', input.label)
            : undefined,
      });
      if (value === undefined) {
        return undefined;
      }
      inputs[input.key] = value;
    }
  }

  return { pullRequestInput, inputs };
}

export type ChildCreatedListener = (child: Prompt, parent: Prompt) => void | Promise<void>;

export function registerGenerateChildCommands(
  context: vscode.ExtensionContext,
  store: PromptStore,
  onChildCreated?: ChildCreatedListener
): void {
  context.subscriptions.push(
    vscode.commands.registerCommand("sobek.linkPlan", async (ref: PromptRef) => {
      const id = resolvePromptId(ref);
      if (!id) {
        return;
      }
      const planPath = await pickPlanFile(store.root);
      if (!planPath) {
        return;
      }
      await store.setLinkedPlan(id, { path: planPath, displayName: path.basename(planPath) });
      void vscode.window.showInformationMessage(vscode.l10n.t("Plan linked: {0}", planPath));
    }),

    vscode.commands.registerCommand("sobek.unlinkPlan", async (ref: PromptRef) => {
      const id = resolvePromptId(ref);
      if (!id) {
        return;
      }
      await store.setLinkedPlan(id, undefined);
    }),

    vscode.commands.registerCommand("sobek.createChildTemplate", async () => {
      const name = await vscode.window.showInputBox({
        prompt: vscode.l10n.t("Name for the custom template"),
        placeHolder: vscode.l10n.t("E.g.: Security review"),
        ignoreFocusOut: true,
        validateInput: (value) =>
          value.trim().length === 0 ? vscode.l10n.t("Enter a name.") : undefined,
      });
      if (!name) {
        return;
      }
      const slug = name
        .trim()
        .normalize("NFD")
        .replace(/[̀-ͯ]/g, "")
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-+|-+$/g, "")
        .slice(0, 48) || "template";
      const filePath = store.customTemplatePath(slug);
      if (!fs.existsSync(filePath)) {
        const skeleton = [
          "---",
          `name: ${name.trim()}`,
          "description: Descreva quando usar este template",
          "targetAgent: ClaudeCode   # ClaudeCode | Codex | Grok",
          "kind: General             # General | Planning",
          "# targetPhaseRole: CodeReview   # opcional — avança a fase do pai (PromptEngineering, Planning, PlanReview, PlanCorrection, Implementation, CodeReview, ReviewCorrection, PracticalTest, Rebase, Merge)",
          "# isReReview: false",
          `title: "${name.trim()}: {DisplayName}"`,
          "# inputs:",
          "#   - key: escopo",
          "#     label: Escopo",
          "#     placeholder: descreva o escopo",
          "#     required: true",
          "#     multiline: false",
          "---",
          `Escreva aqui o conteúdo do prompt filho.`,
          "",
          "Placeholders disponíveis:",
          '- {AbsolutePath} — caminho absoluto do plano vinculado',
          "- {DisplayName} — nome do plano",
          "- {ParentPromptContent} — conteúdo do prompt pai",
          "- {PullRequestReference} — referência de PR (usar torna a PR obrigatória)",
          "- {input:escopo} — valor de um input declarado no frontmatter",
          "",
        ].join("\n");
        await fs.promises.mkdir(store.templatesDir, { recursive: true });
        await fs.promises.writeFile(filePath, skeleton, "utf8");
        await store.reloadCustomTemplates();
      }
      const document = await vscode.workspace.openTextDocument(filePath);
      await vscode.window.showTextDocument(document);
    }),

    vscode.commands.registerCommand("sobek.generateChildPrompt", async (ref: PromptRef) => {
      const id = resolvePromptId(ref);
      if (!id) {
        return;
      }
      let parent = store.require(id);
      if (parent.parentPromptId) {
        void vscode.window.showWarningMessage(
          vscode.l10n.t("Child prompts cannot generate other children.")
        );
        return;
      }
      if (parent.status === "Archived") {
        void vscode.window.showWarningMessage(
          vscode.l10n.t("Archived prompts cannot generate child prompts.")
        );
        return;
      }

      const withPlan = await ensureLinkedPlan(store, parent);
      if (!withPlan?.linkedPlan) {
        return;
      }
      parent = withPlan;
      const plan = parent.linkedPlan!;

      // Broken workspace templates never block the flow; surface them once.
      const templateErrors = store.getCustomTemplateErrors();
      if (templateErrors.length > 0) {
        const openLabel = vscode.l10n.t("Open template");
        void vscode.window
          .showWarningMessage(
            vscode.l10n.t(
              'Invalid custom template "{0}": {1}',
              templateErrors[0].slug,
              templateErrors[0].message
            ),
            openLabel
          )
          .then(async (answer) => {
            if (answer === openLabel) {
              const document = await vscode.workspace.openTextDocument(
                store.customTemplatePath(templateErrors[0].slug)
              );
              await vscode.window.showTextDocument(document);
            }
          });
      }

      type TemplatePick = vscode.QuickPickItem & {
        template?: PromptTemplateDefinition;
        action?: "create";
      };
      const items: TemplatePick[] = getTemplatesInDisplayOrder().map((template) => ({
        label: template.isReReview ? `$(sync) ${template.displayName}` : template.displayName,
        description: template.description,
        template,
      }));
      const customs = store.getCustomTemplates();
      if (customs.length > 0) {
        items.push({
          label: vscode.l10n.t("Workspace templates"),
          kind: vscode.QuickPickItemKind.Separator,
        });
        items.push(
          ...customs.map((template) => ({
            label: `$(file-code) ${template.displayName}`,
            description: template.description,
            template,
          }))
        );
      }
      items.push({ label: "", kind: vscode.QuickPickItemKind.Separator });
      items.push({
        label: `$(add) ${vscode.l10n.t("Create custom template...")}`,
        action: "create",
      });

      const pickedTemplate = await vscode.window.showQuickPick(items, {
        placeHolder: vscode.l10n.t("Child prompt template"),
      });
      if (!pickedTemplate) {
        return;
      }
      if (pickedTemplate.action === "create") {
        await vscode.commands.executeCommand("sobek.createChildTemplate");
        return;
      }
      const template = pickedTemplate.template!;

      const collected = await collectInputs(template, plan.pullRequestReference);
      if (!collected) {
        return;
      }

      let draft;
      try {
        draft = renderPromptDraft({
          template,
          planAbsolutePath: path.resolve(store.root, plan.path),
          planDisplayName: plan.displayName,
          parentPromptContent: parent.content,
          pullRequestInput: collected.pullRequestInput,
          storedPullRequestReference: plan.pullRequestReference,
          inputs: collected.inputs,
        });
      } catch (error) {
        void vscode.window.showErrorMessage((error as Error).message);
        return;
      }

      const title = await vscode.window.showInputBox({
        prompt: vscode.l10n.t("Child prompt title"),
        value: draft.title,
        ignoreFocusOut: true,
        validateInput: (value) =>
          value.trim().length === 0 ? vscode.l10n.t("Enter a title.") : undefined,
      });
      if (!title) {
        return;
      }

      const child = await store.create({
        title: title.trim(),
        content: draft.content,
        parentPromptId: parent.id,
        targetAgent: template.defaultTargetAgent,
        kind: template.defaultKind,
        status: "Draft",
        sourceTemplateKey: template.key,
      });

      if (collected.pullRequestInput?.trim()) {
        await store.setPullRequestReference(parent.id, collected.pullRequestInput.trim());
      }

      // Stay in the parent's context: read-only preview + copy, no navigation
      // to a child edit surface (Thoth product rule).
      const uri = ChildPromptPreviewProvider.uriFor(child.id, child.title);
      const document = await vscode.workspace.openTextDocument(uri);
      await vscode.languages.setTextDocumentLanguage(document, "markdown");
      await vscode.window.showTextDocument(document, { preview: true });

      const updatedParent = store.require(parent.id);
      const phase = updatedParent.workflow?.currentPhaseName;
      const copyLabel = vscode.l10n.t("Copy prompt");
      const action = await vscode.window.showInformationMessage(
        phase
          ? vscode.l10n.t('Child prompt created. Task advanced to "{0}".', phase)
          : vscode.l10n.t("Child prompt created."),
        copyLabel
      );
      if (action === copyLabel) {
        await vscode.env.clipboard.writeText(child.content);
      }

      await onChildCreated?.(child, updatedParent);
    })
  );
}
